server:
  port: 8181
  servlet:
    context-path: /app
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
      
info:
  app:
    name: Spring Boot Assignment 3
    version: 0.0.1
    description: Spring Boot Assignment 2 with actuator
    author: Sumit Sharma