server:
  port: 8181
  servlet:
    context-path: /app
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
      
info:
  app:
    name: Spring Boot Assignment 4
    version: 0.0.1
    description: Spring Boot Assignment 4 with Database
    author: Sumit Sharma
    
spring:
  h2:
    console:
      path : /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb
    username: user
    password: pass
    